--PRIORITY_PERIOD
 CREATE TRIGGER IF NOT EXISTS PRIORITY_PERIOD_DELETE_TRIGGER
	AFTER DELETE ON PRIORITY_PERIOD
	FOR EACH ROW
	WHEN (SELECT COUNT(*) FROM PRIORITY_PERIOD
		WHERE PERIOD_FK = OLD.PERIOD_FK) = 0 AND
		(SELECT COUNT(*) FROM CIRCLE
		WHERE PERIOD_FK = OLD.PERIOD_FK) = 0
	BEGIN
		DELETE FROM PERIOD
			WHERE ID = OLD.PERIOD_FK; END;

 CREATE TRIGGER IF NOT EXISTS PRIORITY_PERIOD_UPDATE_TRIGGER
	AFTER UPDATE OF PERIOD_FK ON PRIORITY_PERIOD
	FOR EACH ROW
	WHEN (SELECT COUNT(*) FROM PRIORITY_PERIOD
		WHERE PERIOD_FK = OLD.PERIOD_FK) = 0 AND
		(SELECT COUNT(*) FROM CIRCLE
		WHERE PERIOD_FK = OLD.PERIOD_FK) = 0
	BEGIN
		DELETE FROM PERIOD
			WHERE ID = OLD.PERIOD_FK; END;

--CIRCLE
 CREATE TRIGGER IF NOT EXISTS CIRCLE_DELETE_TRIGGER
	AFTER DELETE ON CIRCLE
	FOR EACH ROW
	WHEN (SELECT COUNT(*) FROM PRIORITY_PERIOD
		WHERE PERIOD_FK = OLD.PERIOD_FK) = 0 AND
		(SELECT COUNT(*) FROM CIRCLE
		WHERE PERIOD_FK = OLD.PERIOD_FK) = 0
	BEGIN
		DELETE FROM PERIOD
			WHERE ID = OLD.PERIOD_FK; END;

 CREATE TRIGGER IF NOT EXISTS CIRCLE_UPDATE_TRIGGER
	AFTER UPDATE OF PERIOD_FK ON CIRCLE
	FOR EACH ROW
	WHEN (SELECT COUNT(*) FROM PRIORITY_PERIOD
		WHERE PERIOD_FK = OLD.PERIOD_FK) = 0 AND
		(SELECT COUNT(*) FROM CIRCLE
		WHERE PERIOD_FK = OLD.PERIOD_FK) = 0
	BEGIN
		DELETE FROM PERIOD
			WHERE ID = OLD.PERIOD_FK; END;
