--PRIORITY
 CREATE TABLE IF NOT EXISTS PRIORITY(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME VARCHAR NOT NULL);
		
--PRIORITY_PERIOD
 CREATE TABLE IF NOT EXISTS PRIORITY_PERIOD(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	PRIORITY_FK INTEGER NOT NULL REFERENCES PRIORITY(ID),
	PERIOD_FK INTEGER NOT NULL REFERENCES PERIOD(ID));

--PERIOD
 CREATE TABLE IF NOT EXISTS PERIOD(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	MINUTES INTEGER,
	DAYS INTEGER,
	MONTHS INTEGER);

--CIRCLE
 CREATE TABLE IF NOT EXISTS CIRCLE(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	END_DATE DATE,
	PERIOD_FK INTEGER NOT NULL REFERENCES PERIOD(ID));

--CATEGORY
 CREATE TABLE IF NOT EXISTS CATEGORY(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME VARCHAR NOT NULL,
	DESCRIPTION VARCHAR);

--APPOINTMENT_GROUP
 CREATE TABLE IF NOT EXISTS APPOINTMENT_GROUP(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME VARCHAR NOT NULL,
	DESCRIPTION VARCHAR,
	PRIORITY_FK INTEGER NOT NULL REFERENCES PRIORITY(ID),
	CATEGORY_FK INTEGER REFERENCES CATEGORY(ID));

--APPOINTMENT_APPOINTMENT_GROUP
 CREATE TABLE IF NOT EXISTS APPOINTMENT_APPOINTMENT_GROUP(
	APPOINTMENT_FK INTEGER NOT NULL REFERENCES APPOINTMENT(ID),
	APPOINTMENT_GROUP_FK INTEGER NOT NULL REFERENCES APPOINTMENT_GROUP(ID));

--APPOINTMENT
 CREATE TABLE IF NOT EXISTS APPOINTMENT(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	CIRCLE_FK INTEGER REFERENCES CIRCLE(ID));
