--PRIORITY
CREATE TABLE IF NOT EXISTS PRIORITY (
	ID DECIMAL PRIMARY KEY,
	NAME VARCHAR NOT NULL
);

--PERIOD_GROUP
CREATE TABLE IF NOT EXISTS PRIORITY_PERIOD (
	PRIORITY_FK DECIMAL NOT NULL REFERENCES PRIORITY(ID),
	PERIOD_FK DECIMAL NOT NULL REFERENCES PERIOD(ID),
	CONSTRAINT PRIORITY_PERIOD_PK PRIMARY KEY (PRIORITY_FK, PERIOD_FK)
);

--PERIOD
CREATE TABLE IF NOT EXISTS PERIOD (
	ID DECIMAL PRIMARY KEY,
	MINUTES DECIMAL,
	DAYS DECIMAL,
	MONTHS DECIMAL
);

--CYCLE
CREATE TABLE IF NOT EXISTS CYCLE (
	END_DATE DATE,
	PERIOD_FK DECIMAL NOT NULL REFERENCES PERIOD(ID),
	CONSTRAINT CYCLE_PK PRIMARY KEY (END_DATE, PERIOD_FK)
);

--CATEGORY
CREATE TABLE IF NOT EXISTS CATEGORY (
	ID DECIMAL PRIMARY KEY,
	NAME VARCHAR NOT NULL,
	DESCRIPTION VARCHAR
);

--APPOINTMENT_GROUP
CREATE TABLE IF NOT EXISTS APPOINTMENT_GROUP (
	ID DECIMAL PRIMARY KEY,
	NAME VARCHAR NOT NULL,
	DESCRIPTION VARCHAR,
	PRIORITY_FK DECIMAL NOT NULL REFERENCES PRIORITY(ID),
	CATEGORY_FK DECIMAL REFERENCES CATEGORY(ID)
);

--APPOINTMENT_APPOINTMENT_GROUP
CREATE TABLE IF NOT EXISTS APPOINTMENT_APPOINTMENT_GROUP (
	APPOINTMENT_FK DECIMAL NOT NULL REFERENCES APPOINTMENT(ID),
	APPOINTMENT_GROUP_FK DECIMAL NOT NULL REFERENCES APPOINTMENT_GROUP(ID)
);

--APPODECIMALMENT
CREATE TABLE IF NOT EXISTS APPOINTMENT (
	ID DECIMAL PRIMARY KEY,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	CYCLE_FK DECIMAL REFERENCES CYCLE_PK
);
