--PRIORITY_PERIOD
 CREATE
	TRIGGER IF NOT EXISTS PRIORITY_PERIOD_TRIGGER BEFORE DELETE
		OR UPDATE
			ON
			PRIORITY_PERIOD
			WHEN(
				:OLD.PERIOD_FK !=:NEW.PERIOD_FK
			) BEGIN DELETE
			FROM
				PERIOD
			WHERE
				NOT EXISTS(
					SELECT
						NULL
					FROM
						PRIORITY_PERIOD
					WHERE
						PERIOD.PERIOD_PK = PERIOD.PERIOD_FK
				UNION ALL SELECT
						NULL
					FROM
						CIRCLE
					WHERE
						PERIOD.PERIOD_PK = CIRCLE.PERIOD_FK
				UNION ALL
				)
			END;

--CIRCLE
 CREATE
	TRIGGER IF NOT EXISTS CIRCLE_TRIGGER BEFORE DELETE
		OR UPDATE
			ON
			CIRCLE
			WHEN(
				:OLD.PERIOD_FK !=:NEW.PERIOD_FK
			) BEGIN DELETE
			FROM
				PERIOD
			WHERE
				NOT EXISTS(
					SELECT
						NULL
					FROM
						PRIORITY_PERIOD
					WHERE
						PERIOD.PERIOD_PK = PERIOD.PERIOD_FK
				UNION ALL SELECT
						NULL
					FROM
						CIRCLE
					WHERE
						PERIOD.PERIOD_PK = CIRCLE.PERIOD_FK
				UNION ALL
				)
			END;
